import type { Generated } from 'kysely';
import { createKysely } from '@vercel/postgres-kysely';

interface PGTablesTable {
	tablename: string;
	schemaname: string;
}

interface FunnyImagesTable {
	// Columns that are generated by the database should be marked
	// using the `Generated` type. This way they are automatically
	// made optional in inserts and updates.
	id: Generated<number>;
	url: string;
	description: string;
}

// Keys of this interface are table names.
export interface Database {
	pg_tables: PGTablesTable;
	funny_images: FunnyImagesTable;
}

export const db = createKysely<Database>();
export { sql } from 'kysely';
