ALTER TABLE "prompts" ALTER COLUMN "template" DROP DEFAULT;
ALTER TABLE "prompts" ALTER COLUMN "title" DROP DEFAULT;
ALTER TABLE "prompts" ALTER COLUMN "tags" DROP DEFAULT;
ALTER TABLE "prompts" DROP COLUMN IF EXISTS "content";
ALTER TABLE "prompts" DROP COLUMN IF EXISTS "response";