import type { APIRoute } from 'astro';

export const prerender = true; // generates static robots.txt 🤯

// you might consider using `astro-robots-txt` instead of this file
export const get: APIRoute = () => {
	const site = import.meta.env.SITE as string | undefined;
	const siteUrl = site ? new URL(site) : undefined;
	const sitemapEnabled /* B2B:CONFIG */ = false;
	const sitemapUrl = sitemapEnabled && siteUrl ? new URL('/sitemap-index.xml', siteUrl) : undefined;
	// decide when you want your site to be indexed by google, for example only index the production site
	const allowRobots /* B2B:CONFIG */ = import.meta.env.VERCEL_ENV === 'production';

	return new Response(
		`# generated by Astro in src/pages/robots.txt.ts
User-agent: *
${allowRobots ? 'Allow' : 'Disallow'}: /
${siteUrl ? 'Host: ' + siteUrl.host : ''}
${sitemapUrl ? 'Sitemap: ' + sitemapUrl.href : ''}
`,
		{
			headers: {
				'content-type': 'text/plain',
			},
		}
	);
};
