description: Prepares the repo for a typical CI job

name: Prepare
runs:
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: '24'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
